Landing Page Layout
madhurimt/Design_Studio pull request #1
Opened 2022-09-29 08:14 UTC by madhurimt

Tried a basic landing page layout.
![image](https://user-images.githubusercontent.com/105351735/192977602-09ce281a-59c9-4c88-8a7c-8f829e007c78.png)

-Concepts Learnt 
-Creating NavBar using FlexBox
-Positioning

2022-09-29 08:31 UTC, madhurimt commented
Issues:-
- Tried using "<i class="fa-solid fa-arrow-up-right"></i> " but it is not working.

2022-09-30 11:48 UTC, jsjayfiled commented
> 

Those are classes that will display icons on the page.  They are from the 'font awesome' icon library.  Using the library used to be as easy as adding a <link> tag in your <head> then putting classes like "fa-solid fa-arrow-up-right" would give you an icon, but now they want you to sign up and use a different method so I'd avoid them.

But if you want icons I can suggest 'line icons' - [check them out](https://lineicons.com/docs/)

2022-09-30 12:01 UTC, jsjayfiled requested changes

2022-09-30 12:01 UTC, jsjayfiled commented on style.css
> +}
```suggestion
} add a space between the selector (in this case the asterisk *) and the opening brackets - on all css rules
```

2022-09-30 12:02 UTC, jsjayfiled commented
Looks good!
What else are you planning to do to it!

Also, just letting you know that if I am taking too long to get back to you ( I can't check every day 🥹 ) you can merge these yourself.

You are doing really well and should be able to start JS soon :-)

2022-09-30 12:14 UTC, jsjayfiled approved these changes

2022-09-30 12:14 UTC, jsjayfiled commented on style.css
> +    border:1px solid #c9a356;
The design showed a dashed border, you can change this to dashed to get the desired result.

Or if you want to get real fancy you can remove the border property and add in this property instead - it's a little trick to have more control over the dashes

background-image: url("data:image/svg+xml,%3csvg width='100%25' height='100%25' xmlns='http://www.w3.org/2000/svg'%3e%3crect width='100%25' height='100%25' fill='none' stroke='%23333' stroke-width='4' stroke-dasharray='6 14' stroke-dashoffset='0' stroke-linecap='square'/%3e%3c/svg%3e");

stroke-width is a good one to change and the dasharray is how many lines followed by how many gaps

2022-10-03 00:30 UTC, merged